spring:
  datasource:
    url: jdbc:h2:mem:poc
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: true